apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes: #Kuberentes must find an instance of storage that meets these requirements
    - ReadWriteOnce #Get instance of storage that can be used by a single node
  resources:
    requests:
      storage: 2Gi  
      