apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: 'y.khan326@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {} #Basically saying I want to do the http process between let's encrypt and kubernetes cluster